//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mFFramework.Drivers {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DriversRisorse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriversRisorse() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mFFramework.Drivers.DriversRisorse", typeof(DriversRisorse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT count(object_id) CheckSP
        ///FROM sys.objects AS SystemObjects
        ///WHERE SystemObjects.TYPE IN (&apos;P&apos;,&apos;PC&apos;,&apos;X&apos;)
        ///and SystemObjects.name = &apos;@StoredProcedureName&apos;.
        /// </summary>
        internal static string CheckStoredProcedureName {
            get {
                return ResourceManager.GetString("CheckStoredProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT count(id) CheckSP 
        ///FROM dbo.sysobjects 
        ///WHERE id = object_id(N&apos;[dbo].[@StoredProcedureName]&apos;) 
        ///and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1.
        /// </summary>
        internal static string CheckStoredProcedureName_2 {
            get {
                return ResourceManager.GetString("CheckStoredProcedureName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SELECT 
        ///SCHEMA_NAME(SCHEMA_ID) _schema, 
        ///SystemObjects.name  StoredProcedureName,
        ///SystemObjects.Type_Desc  StoredProcedure,
        ///SystemParameters.parameter_id  ParameterID,
        ///SystemParameters.name ParameterName,
        ///TYPE_NAME(SystemParameters.user_type_id) ParameterType,
        ///SystemParameters.max_length ParameterMaxBytes,
        ///SystemParameters.is_output IsOutPutParameter
        ///FROM sys.objects AS SystemObjects
        ///INNER JOIN sys.parameters AS SystemParameters ON SystemObjects.OBJECT_ID = SystemParameters.OBJECT_ID
        ///WHERE System [stringa troncata]&quot;;.
        /// </summary>
        internal static string CheckStoredProcedureParameters {
            get {
                return ResourceManager.GetString("CheckStoredProcedureParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DECLARE @NAME_TRAN VARCHAR(17) = &apos;mFFramework.DBLog&apos;
        ///BEGIN TRY
        ///
        ///	BEGIN TRAN @NAME_TRAN
        ///	
        ///
        ///INSERT INTO @TABELLALOG
        ///           ([MESSAGE]
        ///           ,[STACK_TRACE]
        ///           ,[SOURCE]
        ///           ,[DATA_ERROR]
        ///           ,[ASSEMBLY]
        ///           ,[CLASS]
        ///           ,[METHOD]
        ///           ,[TYPE_ERROR])
        ///     VALUES
        ///           (@MESSAGE
        ///           , CASE WHEN LTRIM(RTRIM(@STACK_TRACE)) = &apos;&apos; THEN NULL
        ///			     ELSE @STACK_TRACE
        ///			     END
        ///           ,@SOURCE
        ///           ,@DATA_ERROR
        ///           , [stringa troncata]&quot;;.
        /// </summary>
        internal static string WriteLog {
            get {
                return ResourceManager.GetString("WriteLog", resourceCulture);
            }
        }
    }
}
